export const CONTENT_ROOM_IDS = [
  "home",
  "bedroom",
  "street",
  "cafe",
  "park",
  "grocery",
] as const;

export type ContentRoomId = typeof CONTENT_ROOM_IDS[number];

export const ADVENTURE_IDS = [
  "home-helper",
  "story-time",
  "kitchen-creator",
  "self-care-star",
  "neighborhood-friend",
  "scooter-story",
  "cafe-helper",
  "park-caretaker",
  "playground-fun",
  "picnic-planner",
  "smart-shopper",
  "photo-story",
  "world-explorer",
] as const;

export type AdventureId = typeof ADVENTURE_IDS[number];

export interface AdventureDefinition {
  id: AdventureId;
  title: string;
  description: string;
  hint: string;
  room: ContentRoomId | "any";
  roomLabel: string;
  icon: string;
  sticker: string;
  stickerLabel: string;
  stars: number;
}

export const ADVENTURES: readonly AdventureDefinition[] = [
  {
    id: "home-helper",
    title: "Home Helper",
    description: "Clean, tidy, or put something safely away.",
    hint: "Try the sponge, book shelf, wardrobe, sink, or bin.",
    room: "home",
    roomLabel: "Family Home",
    icon: "🧽",
    sticker: "✨",
    stickerLabel: "Sparkle Helper",
    stars: 2,
  },
  {
    id: "story-time",
    title: "Story Time",
    description: "Pick up the book and read a cozy story.",
    hint: "The book can be found at home or in Khadija's bedroom.",
    room: "bedroom",
    roomLabel: "Bedroom",
    icon: "📖",
    sticker: "📚",
    stickerLabel: "Story Star",
    stars: 2,
  },
  {
    id: "kitchen-creator",
    title: "Kitchen Creator",
    description: "Finish a pretend recipe at a kitchen station.",
    hint: "Try bread and cheese, fruit in the bowl, tea, toast, or cake mix.",
    room: "home",
    roomLabel: "Family Home",
    icon: "🥣",
    sticker: "👩🏽‍🍳",
    stickerLabel: "Kitchen Creator",
    stars: 3,
  },
  {
    id: "self-care-star",
    title: "Self-Care Star",
    description: "Wash, brush, bathe, dry off, or smile in the mirror.",
    hint: "Explore the ensuite bathroom in Khadija's bedroom.",
    room: "bedroom",
    roomLabel: "Bedroom",
    icon: "🫧",
    sticker: "🌟",
    stickerLabel: "Self-Care Star",
    stars: 2,
  },
  {
    id: "neighborhood-friend",
    title: "Neighborhood Friend",
    description: "Share an activity or give a kind gift to a neighbor.",
    hint: "Talk, play together, or hand an item to a nearby friend.",
    room: "street",
    roomLabel: "Neighborhood",
    icon: "🤝",
    sticker: "💛",
    stickerLabel: "Kind Neighbor",
    stars: 3,
  },
  {
    id: "scooter-story",
    title: "Scooter Story",
    description: "Take Khadija for a cheerful scooter ride.",
    hint: "Find the scooter in the neighborhood and tap it.",
    room: "street",
    roomLabel: "Neighborhood",
    icon: "🛴",
    sticker: "💨",
    stickerLabel: "Scooter Explorer",
    stars: 2,
  },
  {
    id: "cafe-helper",
    title: "Sunny Café Helper",
    description: "Order a treat or warm drink, ring the bell, or return a dish.",
    hint: "Explore the counter, pastry display, hot drinks, and return tray.",
    room: "cafe",
    roomLabel: "Sunny Café",
    icon: "☕",
    sticker: "🧁",
    stickerLabel: "Café Helper",
    stars: 2,
  },
  {
    id: "park-caretaker",
    title: "Park Caretaker",
    description: "Help the flowers, birds, or park tidy-up.",
    hint: "Use the watering can, bring fruit or bread, or find the wrapper.",
    room: "park",
    roomLabel: "Park",
    icon: "🌱",
    sticker: "🌼",
    stickerLabel: "Nature Helper",
    stars: 3,
  },
  {
    id: "playground-fun",
    title: "Playground Fun",
    description: "Try the slide, swings, or sandbox.",
    hint: "Tap one of the playground activities in the park.",
    room: "park",
    roomLabel: "Park",
    icon: "🛝",
    sticker: "🎈",
    stickerLabel: "Playground Pal",
    stars: 2,
  },
  {
    id: "picnic-planner",
    title: "Picnic Planner",
    description: "Bring a snack or drink to the picnic blanket.",
    hint: "Hold something tasty, then tap the picnic spot.",
    room: "park",
    roomLabel: "Park",
    icon: "🧺",
    sticker: "🍓",
    stickerLabel: "Picnic Planner",
    stars: 2,
  },
  {
    id: "smart-shopper",
    title: "Smart Shopper",
    description: "Choose groceries and pack them at the checkout.",
    hint: "Carry the shopping basket, choose items, then visit the checkout.",
    room: "grocery",
    roomLabel: "Sunny Basket",
    icon: "🛍️",
    sticker: "🥕",
    stickerLabel: "Smart Shopper",
    stars: 3,
  },
  {
    id: "photo-story",
    title: "Photo Story",
    description: "Use the camera to make a pretend story-album photo.",
    hint: "Pick up the camera in the park and use it.",
    room: "park",
    roomLabel: "Park",
    icon: "📷",
    sticker: "🖼️",
    stickerLabel: "Story Photographer",
    stars: 2,
  },
  {
    id: "world-explorer",
    title: "World Explorer",
    description: "Visit every place in Khadija's neighborhood.",
    hint: "Explore Home, Bedroom, Neighborhood, Café, Park, and Grocery.",
    room: "any",
    roomLabel: "Everywhere",
    icon: "🗺️",
    sticker: "🏆",
    stickerLabel: "World Explorer",
    stars: 5,
  },
] as const;
